# Generated by Django 3.1 on 2020-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=100)),
                ('Subname', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.IntegerField(default=0)),
                ('Cname', models.CharField(max_length=100)),
                ('Subname', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection1',
            fields=[
                ('Subid', models.IntegerField(primary_key=True, serialize=False)),
                ('Subname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionDetail',
            fields=[
                ('Subid', models.IntegerField(primary_key=True, serialize=False)),
                ('Subname', models.CharField(max_length=100)),
                ('Sname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='product1',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='A valid price is non-negative'),
        ),
    ]
