# Generated by Django 3.1 on 2020-08-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Cid', models.IntegerField(primary_key=True, serialize=False)),
                ('Cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('amount', models.IntegerField(default=0)),
                ('incategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('Subid', models.IntegerField(primary_key=True, serialize=False)),
                ('Subname', models.CharField(max_length=100)),
                ('insection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.section')),
            ],
        ),
        migrations.DeleteModel(
            name='Category1',
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.DeleteModel(
            name='Section1',
        ),
        migrations.DeleteModel(
            name='Subsection1',
        ),
        migrations.AddField(
            model_name='category',
            name='insubsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopapp.subsection'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='A valid price is non-negative'),
        ),
    ]
